### ISSUE TITLE
Allow functionality for non registered users

### ISSUE THREAD

**Issue by planetahuevo** [ploi-deploy/roadmap#98]
I would like to know if it is possible to allow non registered users to vote, and maybe to be able to add feature requests.

I understand that will make the votes count less trustworthy, but it also will allow more people to give feedback and ideas without the need to login or register into another app/website. 

Maybe a captcha to prevent submit feature request from bots?
Or an approval queue? 

I know this is not an easy thing to build, and maybe it could be stripped into several smaller tasks, but I would love to hear what do you think. 
Thanks!

**Comment by Cannonb4ll** [comment]
It would be possible for sure, I won't probably need it in the near future so if you're willing to build this and PR this I'm willing to merge that. Important thing is that it has to be configurable so that admins can allow guests to vote or not.

If you're going to build this, I'd prefer to use an IP check of some kind.

**Comment by planetahuevo** [comment]
I have no idea how to program such things. :) 
I am good thinking, testing, and all that, but you do not want a PR from me. :D 
So I will play a little more with the software and think about how this could be done easily. 
And if I need it (which I will in the future) I will try to get a developer to build it together and do that PR. 👍 
Thanks!

**Comment by Cannonb4ll** [comment]
Sure thing, I'll close this for now as I am not planning this, whenever we want, we can re-open this!
